## 1. Importing pandas

In [1]:
import pandas as pd

## 2. Opening a local csv file

In [3]:
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv')
df.head()

,Season,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
0,1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1,1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
2,1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
3,1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
4,1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier

## 3. Opening a csv file from an url

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/aayushmanz/Python-For-Data-Science/main/Database%20from%20Kaggle/kohli_ipl.csv')
df

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

## 4. using sep Parameter :

In [7]:
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/file.tsv', sep='\t')
df

          0    50  5  881250949
0         0   172  5  881250949
1         0   133  1  881250949
2       196   242  3  881250949
3       186   302  3  891717742
4        22   377  1  878887116
...     ...   ... ..        ...
99997   880   476  3  880175444
99998   716   204  5  879795543
99999   276  1090  1  874795795
100000   13   225  2  882399156
100001   12   203  3  879959583

[100002 rows x 4 columns]

## 5. Rename column in CSV :

In [ ]:
# new way :

# this is just a dumpy don't take the columns name seriously
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/file.tsv', sep='\t', names=['sno','name', 'release_year', 'number'])
df

        sno  name  release_year      genre
0         0    50             5  881250949
1         0   172             5  881250949
2         0   133             1  881250949
3       196   242             3  881250949
4       186   302             3  891717742
...     ...   ...           ...        ...
99998   880   476             3  880175444
99999   716   204             5  879795543
100000  276  1090             1  874795795
100001   13   225             2  882399156
100002   12   203             3  879959583

[100003 rows x 4 columns]

In [11]:
# old way :

df = pd.read_csv('https://raw.githubusercontent.com/aayushmanz/Python-For-Data-Science/main/Database%20from%20Kaggle/kohli_ipl.csv')
df.head()

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [ ]:
df = df.rename(columns={
    'match_no':'Match_No',
    'runs' : 'Runs'
})

df  # this more precise way to rename the columns.

     Match_No  Runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

## 5. Index_col Parameter :

In [18]:
# new way :
pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv',index_col='Season' ).head()

,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
Season,,,,,,,,
1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier

In [20]:
# old way ;

df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv')

df.set_index('Season').head() # old but far useful.

,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
Season,,,,,,,,
1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier

## 6. Header Parameter :

In [ ]:
pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/test.csv', header=1)

,5,A,B,A.1,C,B.1,C.1,A.2,E,C.2,...,0.2855085705475974,0.8600457644522872,0.7987116316548636,0.8359614405089484,0.39165722874936104,0.2882755588329365,0.5495675805096408,0.9050972328167228,0.8506839425302345,0.6939397082927241
0,15,B,A,A,A,B,B,A,E,D,...,0.697272,0.683600,0.404089,0.879379,0.275549,0.427871,0.491667,0.384315,0.376689,0.508099
1,16,B,B,A,C,B,D,A,E,A,...,0.719306,0.777890,0.730954,0.644315,1.024017,0.391090,0.988340,0.411828,0.393585,0.461372
2,17,B,B,A,C,B,C,A,E,C,...,0.313032,0.431007,0.390992,0.408874,0.447887,0.390253,0.648932,0.385935,0.370401,0.900412
3,19,B,B,B,C,B,B,A,E,E,...,0.489711,0.533519,0.451563,0.513817,0.429349,0.489093,0.326913,0.440908,0.694076,0.444859
4,20,A,A,A,C,B,D,A,E,G,...,0.285503,0.497190,0.540631,0.521383,0.277155,0.837442,0.602099,1.057592,0.522523,0.668214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199993,499987,B,A,A,C,B,D,A,E,E,...,0.287454,0.543800,0.682378,1.028978,1.022741,0.683903,0.877273,0.532410,0.605397,0.884581
199994,499990,B,A,A,C,B,B,A,E,C,...,0.794881,0.432778,0.389775,0.359871,0.550013,0.492082,0.202295,0.416875,0.406205,0.758665
199995,499991,A,B,B,C,B,B,A,E,C,...,0.514487,0.060997,0.171741,0.317185,0.150340,0.122109,0.390524,0.334026,0.378987,0.839416
199996,499994,A,A,A,C,B,D,A,D,A,...,0.286144,1.061710,0.819811,0.901241,0.555339,0.844315,0.894193,0.794102,0.844279,0.890473
199997,499995,A,A,A,C,B,D,A,E,A,...,0.286755,1.065725,0.687682,0.654738,0.574575,0.617467,0.694336,0.745698,0.568525,0.783568