## 1. Importing pandas

In [1]:
import pandas as pd

## 2. Opening a local csv file

In [2]:
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv')
df.head()

,Season,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
0,1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1,1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
2,1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
3,1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
4,1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier

## 3. Opening a csv file from an url

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/aayushmanz/Python-For-Data-Science/main/Database%20from%20Kaggle/kohli_ipl.csv')
df

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

## 4. using sep Parameter :

In [4]:
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/file.tsv', sep='\t')
df

          0    50  5  881250949
0         0   172  5  881250949
1         0   133  1  881250949
2       196   242  3  881250949
3       186   302  3  891717742
4        22   377  1  878887116
...     ...   ... ..        ...
99997   880   476  3  880175444
99998   716   204  5  879795543
99999   276  1090  1  874795795
100000   13   225  2  882399156
100001   12   203  3  879959583

[100002 rows x 4 columns]

## 5. Rename column in CSV :

In [5]:
# new way :

# this is just a dumpy don't take the columns name seriously
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/file.tsv', sep='\t', names=['sno','name', 'release_year', 'number'])
df

        sno  name  release_year     number
0         0    50             5  881250949
1         0   172             5  881250949
2         0   133             1  881250949
3       196   242             3  881250949
4       186   302             3  891717742
...     ...   ...           ...        ...
99998   880   476             3  880175444
99999   716   204             5  879795543
100000  276  1090             1  874795795
100001   13   225             2  882399156
100002   12   203             3  879959583

[100003 rows x 4 columns]

In [6]:
# old way :

df = pd.read_csv('https://raw.githubusercontent.com/aayushmanz/Python-For-Data-Science/main/Database%20from%20Kaggle/kohli_ipl.csv')
df.head()

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [7]:
df = df.rename(columns={
    'match_no':'Match_No',
    'runs' : 'Runs'
})

df  # this more precise way to rename the columns.

     Match_No  Runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

## 5. Index_col Parameter :

In [8]:
# new way :
pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv',index_col='Season' ).head()

,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
Season,,,,,,,,
1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier

In [9]:
# old way ;

df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv')

df.set_index('Season').head() # old but far useful.

,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
Season,,,,,,,,
1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier

## 6. Header Parameter :

In [10]:
pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/test.csv', header=1)

,0,B,B.1,B.2,C,B.3,B.4,A,E,E.1,...,0.4767390451101133,0.37634964704960105,0.3378838967546349,0.3218317548420124,0.4452123032588636,0.2902576164838725,0.24447618266447746,0.08791370093201539,0.3018314255545636,0.8457015400873743
0,5,A,B,A,C,B,C,A,E,C,...,0.285509,0.860046,0.798712,0.835961,0.391657,0.288276,0.549568,0.905097,0.850684,0.693940
1,15,B,A,A,A,B,B,A,E,D,...,0.697272,0.683600,0.404089,0.879379,0.275549,0.427871,0.491667,0.384315,0.376689,0.508099
2,16,B,B,A,C,B,D,A,E,A,...,0.719306,0.777890,0.730954,0.644315,1.024017,0.391090,0.988340,0.411828,0.393585,0.461372
3,17,B,B,A,C,B,C,A,E,C,...,0.313032,0.431007,0.390992,0.408874,0.447887,0.390253,0.648932,0.385935,0.370401,0.900412
4,19,B,B,B,C,B,B,A,E,E,...,0.489711,0.533519,0.451563,0.513817,0.429349,0.489093,0.326913,0.440908,0.694076,0.444859
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199994,499987,B,A,A,C,B,D,A,E,E,...,0.287454,0.543800,0.682378,1.028978,1.022741,0.683903,0.877273,0.532410,0.605397,0.884581
199995,499990,B,A,A,C,B,B,A,E,C,...,0.794881,0.432778,0.389775,0.359871,0.550013,0.492082,0.202295,0.416875,0.406205,0.758665
199996,499991,A,B,B,C,B,B,A,E,C,...,0.514487,0.060997,0.171741,0.317185,0.150340,0.122109,0.390524,0.334026,0.378987,0.839416
199997,499994,A,A,A,C,B,D,A,D,A,...,0.286144,1.061710,0.819811,0.901241,0.555339,0.844315,0.894193,0.794102,0.844279,0.890473
199998,499995,A,A,A,C,B,D,A,E,A,...,0.286755,1.065725,0.687682,0.654738,0.574575,0.617467,0.694336,0.745698,0.568525,0.783568

## 7. use_cols parameter

In [11]:
# new way to use the read_csv for columns  

pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv', usecols=['Season','Country', 'Round'])

      Season  Round         Country
0       1950      1  United Kingdom
1       1950      2          Monaco
2       1950      3   United States
3       1950      4     Switzerland
4       1950      5         Belgium
...      ...    ...             ...
1153    2026      5          Canada
1154    2026      6          Monaco
1155    2026      7           Spain
1156    2026      8         Austria
1157    2026      9  United Kingdom

[1158 rows x 3 columns]

In [12]:
# one more wayb to do that through iloc and loc 

df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv')
df[:,['Season', 'Country']] # df[['Season', 'Country']]

InvalidIndexError: (slice(None, None, None), ['Season', 'Country'])

In [ ]:
# iloc :

df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv')
df.iloc[:,1:4:1]

                          Grand Prix  Round   Race Date
0                 British Grand Prix      1  1950-05-13
1                  Monaco Grand Prix      2  1950-05-21
2                   Indianapolis 500      3  1950-05-30
3                   Swiss Grand Prix      4  1950-06-04
4                 Belgian Grand Prix      5  1950-06-18
...                              ...    ...         ...
1153             Canadian Grand Prix      5  2026-05-24
1154               Monaco Grand Prix      6  2026-06-07
1155  Barcelona-Catalunya Grand Prix      7  2026-06-14
1156             Austrian Grand Prix      8  2026-06-28
1157              British Grand Prix      9  2026-07-05

[1158 rows x 3 columns]

## 8. Squeeze parameter :

In [ ]:
# df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv', usecols=['Country'], squeeze=True)
# squeeze is not avaiable for new update of pandas.

## 9. Skiprows / nrows Parameter

In [ ]:
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv', skiprows=[0,1])
df

,1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
0,1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
1,1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
2,1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier
3,1950,French Grand Prix,6,1950-07-02,Reims-Gueux,France,Juan Manuel Fangio,Luigi Fagioli,Peter Whitehead
4,1950,Italian Grand Prix,7,1950-09-03,Autodromo Nazionale di Monza,Italy,Giuseppe Farina,Alberto Ascari,Luigi Fagioli
...,...,...,...,...,...,...,...,...,...
1151,2026,Canadian Grand Prix,5,2026-05-24,Circuit Gilles Villeneuve,Canada,Kimi Antonelli,Lewis Hamilton,Max Verstappen
1152,2026,Monaco Grand Prix,6,2026-06-07,Circuit de Monaco,Monaco,Kimi Antonelli,Lewis Hamilton,Isack Hadjar
1153,2026,Barcelona-Catalunya Grand Prix,7,2026-06-14,Circuit de Barcelona-Catalunya,Spain,Lewis Hamilton,George Russell,Lando Norris
1154,2026,Austrian Grand Prix,8,2026-06-28,Red Bull Ring,Austria,George Russell,Max Verstappen,Kimi Antonelli
1155,2026,British Grand Prix,9,2026-07-05,Silverstone Circuit,United Kingdom,Charles Leclerc,George Russell,Lewis Hamilton

In [14]:
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv', nrows=10)
df

,Season,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
0,1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1,1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
2,1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
3,1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
4,1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier
5,1950,French Grand Prix,6,1950-07-02,Reims-Gueux,France,Juan Manuel Fangio,Luigi Fagioli,Peter Whitehead
6,1950,Italian Grand Prix,7,1950-09-03,Autodromo Nazionale di Monza,Italy,Giuseppe Farina,Alberto Ascari,Luigi Fagioli
7,1951,Swiss Grand Prix,1,1951-05-27,Circuit Bremgarten,Switzerland,Juan Manuel Fangio,Piero Taruffi,Giuseppe Farina
8,1951,Indianapolis 500,2,1951-05-30,Indianapolis Motor Speedway,United States,Lee Wallard,Mike Nazaruk,Jack McGrath / Manny Ayulo
9,1951,Belgian Grand Prix,3,1951-06-17,Circuit de Spa-Francorchamps,Belgium,Giuseppe Farina,Alberto Ascari,Luigi Villoresi

## 10. Encoding

In [16]:
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv', encoding='latin-1')
df.head(2)

,Season,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
0,1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1,1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron

## 11. dtypes parameter :