## 1. Importing pandas

In [1]:
import pandas as pd

## 2. Opening a local csv file

In [3]:
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv')
df.head()

,Season,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
0,1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1,1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
2,1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
3,1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
4,1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier

## 3. Opening a csv file from an url

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/aayushmanz/Python-For-Data-Science/main/Database%20from%20Kaggle/kohli_ipl.csv')
df

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

## 4. using sep Parameter :

In [7]:
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/file.tsv', sep='\t')
df

          0    50  5  881250949
0         0   172  5  881250949
1         0   133  1  881250949
2       196   242  3  881250949
3       186   302  3  891717742
4        22   377  1  878887116
...     ...   ... ..        ...
99997   880   476  3  880175444
99998   716   204  5  879795543
99999   276  1090  1  874795795
100000   13   225  2  882399156
100001   12   203  3  879959583

[100002 rows x 4 columns]

## 5. Rename column in CSV :

In [ ]:
# new way :

# this is just a dumpy don't take the columns name seriously
df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/file.tsv', sep='\t', names=['sno','name', 'release_year', 'number'])
df

        sno  name  release_year      genre
0         0    50             5  881250949
1         0   172             5  881250949
2         0   133             1  881250949
3       196   242             3  881250949
4       186   302             3  891717742
...     ...   ...           ...        ...
99998   880   476             3  880175444
99999   716   204             5  879795543
100000  276  1090             1  874795795
100001   13   225             2  882399156
100002   12   203             3  879959583

[100003 rows x 4 columns]

In [11]:
# old way :

df = pd.read_csv('https://raw.githubusercontent.com/aayushmanz/Python-For-Data-Science/main/Database%20from%20Kaggle/kohli_ipl.csv')
df.head()

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [ ]:
df = df.rename(columns={
    'match_no':'Match_No',
    'runs' : 'Runs'
})

df  # this more precise way to rename the columns.

     Match_No  Runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

## 5. Index_col Parameter :

In [18]:
# new way :
pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv',index_col='Season' ).head()

,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
Season,,,,,,,,
1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier

In [20]:
# old way ;

df = pd.read_csv('/workspaces/Machine-Learning-with-Python/Data Gathering & File Handling/f1_podiums_1950_2026.csv')

df.set_index('Season').head() # old but far useful.

,Grand Prix,Round,Race Date,Circuit,Country,Winner,Second Place Driver,Third Place Driver
Season,,,,,,,,
1950,British Grand Prix,1,1950-05-13,Silverstone Circuit,United Kingdom,Giuseppe Farina,Luigi Fagioli,Reg Parnell
1950,Monaco Grand Prix,2,1950-05-21,Circuit de Monaco,Monaco,Juan Manuel Fangio,Alberto Ascari,Louis Chiron
1950,Indianapolis 500,3,1950-05-30,Indianapolis Motor Speedway,United States,Johnnie Parsons,Bill Holland,Mauri Rose
1950,Swiss Grand Prix,4,1950-06-04,Circuit Bremgarten,Switzerland,Giuseppe Farina,Luigi Fagioli,Louis Rosier
1950,Belgian Grand Prix,5,1950-06-18,Circuit de Spa-Francorchamps,Belgium,Juan Manuel Fangio,Luigi Fagioli,Louis Rosier

## 6. Header Parameter :